### ISSUE TITLE
Testing...

### ISSUE THREAD

**Issue by robgraves** [danshadeck/spg1#1]
Testing issue section on github.  i haven't used this on here yet.

[http://lab46.corning-cc.edu/opus/spring2015/mp010784/start](http://lab46.corning-cc.edu/opus/spring2015/mp010784/start)

**Comment by danshadeck** [comment]
appears to be working well! nice!

**Comment by justgolden07** [comment]
nothing like a close up picture after clicking a link!

**Comment by robgraves** [comment]
lol

**Comment by robgraves** [comment]
my opus rocks
