### ISSUE TITLE
Meeting up over break week

### ISSUE THREAD

**Issue by robgraves** [danshadeck/spg1#4]
You guys have any preference of days to meet up over break week to work on this?

**Comment by danshadeck** [comment]
I'm completely open! What about you Zach?

**Comment by justgolden07** [comment]
I'm good whenever just text me, I dont really look at me email and forget
about github a lot

**Comment by robgraves** [comment]
ok monday or tuesday? for first one?
...i'll just text you guys

**Comment by robgraves** [comment]
Ok I added a winflag and ladderflag to the output of the debug messages in my printlocation function to monitor the states of these variables as mario moves, the output goes to the terminal that runs the game, also this version is currently only located in the matt subdirectory of the repo.

**Comment by robgraves** [comment]
![mariodebug](https://cloud.githubusercontent.com/assets/1985693/6260173/d70b6b20-b7a8-11e4-9356-b552e703437f.png)

**Comment by robgraves** [comment]
Ok now I got it to actually break out of the game when the desired coordinates are reached, the "win condition" and I did it without using the winflag, thus rendering this variable pointless.

**Comment by robgraves** [comment]
added cheesy low budget "YOU WIN!" (hand drawn in GIMP in less than 5 seconds) message to win condition int he form of end.bmp file.

**Comment by robgraves** [comment]
![mariowin](https://cloud.githubusercontent.com/assets/1985693/6260715/e386e322-b7b0-11e4-8432-d9fbe8a5c780.png)
LOL!!!!

**Comment by justgolden07** [comment]
Perfect 10/10 stars! Encore!

**Comment by justgolden07** [comment]
http://s11.photobucket.com/user/pirhanachomp/media/mario1up.gif.html how bout this?

**Comment by robgraves** [comment]
LMFAO, if i can get it to load a gif that would be great!

**Comment by robgraves** [comment]
i had trouble finding anythign clear as to how to animate a gif in SDL, most people said it only shows the one frame, so i had the gif split into its seperate frames, then used SDL2 to create a while loop at the end of th ecode to animate the frames from the gif, also added on most recent push a single variable to control the delay for one stop change to speed up or slow down the animation.

**Comment by robgraves** [comment]
btw the "merely you win" end sequence is in the main directory of the repo, the "mario gif animated via SDL while loop" is in the matt subdirectory.

**Comment by robgraves** [comment]
closed, break over
success?
